# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e186462db722c30110e045afebf18a98a1152df77e4c1ed97480722bfb523ed03dd693cd9dbe3f213e98dc40c12e0fe57f687c829741255822fa4792eefe2c65

test:
  secret_key_base: 871e9342a4806d56dfcf00c19773926c8292526ae880e738a9cb4bcf483b830908f206cebbd8aa98091edc3e783bdf63a8f4ad0255852a4a3b4e17d5fa31131c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
